set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
# clk => 100000000Hz
create_clock -period 10.0 -name clk_0 -waveform {0.000 5.000} [get_ports clk]
set_property PACKAGE_PIN P6 [get_ports {rstN}]
set_property IOSTANDARD LVCMOS33 [get_ports {rstN}]
set_property PACKAGE_PIN K13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN L14 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN L13 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN M16 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN M14 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN M12 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN N16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN P15 [get_ports {usbRx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usbRx}]
set_property PACKAGE_PIN P16 [get_ports {usbTx}]
set_property IOSTANDARD LVCMOS33 [get_ports {usbTx}]
set_property PACKAGE_PIN B6 [get_ports {ioLed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[0]}]
set_property PACKAGE_PIN B5 [get_ports {ioLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[1]}]
set_property PACKAGE_PIN A5 [get_ports {ioLed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[2]}]
set_property PACKAGE_PIN A4 [get_ports {ioLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[3]}]
set_property PACKAGE_PIN B4 [get_ports {ioLed[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[4]}]
set_property PACKAGE_PIN A3 [get_ports {ioLed[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[5]}]
set_property PACKAGE_PIN F4 [get_ports {ioLed[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[6]}]
set_property PACKAGE_PIN F3 [get_ports {ioLed[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[7]}]
set_property PACKAGE_PIN F2 [get_ports {ioLed[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[8]}]
set_property PACKAGE_PIN E1 [get_ports {ioLed[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[9]}]
set_property PACKAGE_PIN B2 [get_ports {ioLed[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[10]}]
set_property PACKAGE_PIN A2 [get_ports {ioLed[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[11]}]
set_property PACKAGE_PIN E2 [get_ports {ioLed[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[12]}]
set_property PACKAGE_PIN D1 [get_ports {ioLed[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[13]}]
set_property PACKAGE_PIN E6 [get_ports {ioLed[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[14]}]
set_property PACKAGE_PIN K5 [get_ports {ioLed[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[15]}]
set_property PACKAGE_PIN G2 [get_ports {ioLed[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[16]}]
set_property PACKAGE_PIN G1 [get_ports {ioLed[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[17]}]
set_property PACKAGE_PIN H2 [get_ports {ioLed[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[18]}]
set_property PACKAGE_PIN H1 [get_ports {ioLed[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[19]}]
set_property PACKAGE_PIN K1 [get_ports {ioLed[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[20]}]
set_property PACKAGE_PIN J1 [get_ports {ioLed[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[21]}]
set_property PACKAGE_PIN L3 [get_ports {ioLed[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[22]}]
set_property PACKAGE_PIN L2 [get_ports {ioLed[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioLed[23]}]

# set_property PACKAGE_PIN D6 [get_ports {ioDip[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[0]}]
# set_property PULLDOWN true [get_ports {ioDip[0]}]
# set_property PACKAGE_PIN D5 [get_ports {ioDip[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[1]}]
# set_property PULLDOWN true [get_ports {ioDip[1]}]
# set_property PACKAGE_PIN F5 [get_ports {ioDip[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[2]}]
# set_property PULLDOWN true [get_ports {ioDip[2]}]
# set_property PACKAGE_PIN E5 [get_ports {ioDip[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[3]}]
# set_property PULLDOWN true [get_ports {ioDip[3]}]
# set_property PACKAGE_PIN G5 [get_ports {ioDip[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[4]}]
# set_property PULLDOWN true [get_ports {ioDip[4]}]
# set_property PACKAGE_PIN G4 [get_ports {ioDip[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[5]}]
# set_property PULLDOWN true [get_ports {ioDip[5]}]
# set_property PACKAGE_PIN D4 [get_ports {ioDip[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[6]}]
# set_property PULLDOWN true [get_ports {ioDip[6]}]
# set_property PACKAGE_PIN C4 [get_ports {ioDip[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[7]}]
# set_property PULLDOWN true [get_ports {ioDip[7]}]
# set_property PACKAGE_PIN E3 [get_ports {ioDip[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[8]}]
# set_property PULLDOWN true [get_ports {ioDip[8]}]
# set_property PACKAGE_PIN D3 [get_ports {ioDip[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[9]}]
# set_property PULLDOWN true [get_ports {ioDip[9]}]
# set_property PACKAGE_PIN C3 [get_ports {ioDip[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[10]}]
# set_property PULLDOWN true [get_ports {ioDip[10]}]
# set_property PACKAGE_PIN C2 [get_ports {ioDip[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[11]}]
# set_property PULLDOWN true [get_ports {ioDip[11]}]
# set_property PACKAGE_PIN C1 [get_ports {ioDip[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[12]}]
# set_property PULLDOWN true [get_ports {ioDip[12]}]
# set_property PACKAGE_PIN B1 [get_ports {ioDip[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[13]}]
# set_property PULLDOWN true [get_ports {ioDip[13]}]
# set_property PACKAGE_PIN M6 [get_ports {ioDip[14]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[14]}]
# set_property PULLDOWN true [get_ports {ioDip[14]}]
# set_property PACKAGE_PIN N6 [get_ports {ioDip[15]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[15]}]
# set_property PULLDOWN true [get_ports {ioDip[15]}]
# set_property PACKAGE_PIN H5 [get_ports {ioDip[16]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[16]}]
# set_property PULLDOWN true [get_ports {ioDip[16]}]
# set_property PACKAGE_PIN H4 [get_ports {ioDip[17]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[17]}]
# set_property PULLDOWN true [get_ports {ioDip[17]}]
# set_property PACKAGE_PIN J3 [get_ports {ioDip[18]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[18]}]
# set_property PULLDOWN true [get_ports {ioDip[18]}]
# set_property PACKAGE_PIN H3 [get_ports {ioDip[19]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[19]}]
# set_property PULLDOWN true [get_ports {ioDip[19]}]
# set_property PACKAGE_PIN J5 [get_ports {ioDip[20]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[20]}]
# set_property PULLDOWN true [get_ports {ioDip[20]}]
# set_property PACKAGE_PIN J4 [get_ports {ioDip[21]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[21]}]
# set_property PULLDOWN true [get_ports {ioDip[21]}]
# set_property PACKAGE_PIN K3 [get_ports {ioDip[22]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[22]}]
# set_property PULLDOWN true [get_ports {ioDip[22]}]
# set_property PACKAGE_PIN K2 [get_ports {ioDip[23]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioDip[23]}]
# set_property PULLDOWN true [get_ports {ioDip[23]}]

# set_property PACKAGE_PIN C6 [get_ports {ioButton[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioButton[0]}]
# set_property PULLDOWN true [get_ports {ioButton[0]}]
# set_property PACKAGE_PIN C7 [get_ports {ioButton[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioButton[1]}]
# set_property PULLDOWN true [get_ports {ioButton[1]}]
# set_property PACKAGE_PIN A7 [get_ports {ioButton[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioButton[2]}]
# set_property PULLDOWN true [get_ports {ioButton[2]}]
# set_property PACKAGE_PIN B7 [get_ports {ioButton[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioButton[3]}]
# set_property PULLDOWN true [get_ports {ioButton[3]}]
# set_property PACKAGE_PIN P11 [get_ports {ioButton[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ioButton[4]}]
# set_property PULLDOWN true [get_ports {ioButton[4]}]

set_property PACKAGE_PIN P8 [get_ports {ioSel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSel[0]}]
set_property PACKAGE_PIN R8 [get_ports {ioSel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSel[1]}]
set_property PACKAGE_PIN N9 [get_ports {ioSel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSel[2]}]
set_property PACKAGE_PIN P9 [get_ports {ioSel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSel[3]}]
set_property PACKAGE_PIN T5 [get_ports {ioSeg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[0]}]
set_property PACKAGE_PIN R5 [get_ports {ioSeg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[1]}]
set_property PACKAGE_PIN T9 [get_ports {ioSeg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[2]}]
set_property PACKAGE_PIN R6 [get_ports {ioSeg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[3]}]
set_property PACKAGE_PIN R7 [get_ports {ioSeg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[4]}]
set_property PACKAGE_PIN T7 [get_ports {ioSeg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[5]}]
set_property PACKAGE_PIN T8 [get_ports {ioSeg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[6]}]
set_property PACKAGE_PIN T10 [get_ports {ioSeg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioSeg[7]}]